name: Continuous Integration Workflow

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: checkout-repo
      uses: actions/checkout@v4

    - name: install-python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: make venv - get dependencies - run pytest
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        cd api
        pip install -r requirements.txt
        pytest
        cd ..
        cd pipeline
        pip install -r requirements.txt
        pytest
        cd ..
        cd database
        pip install -r requirements.txt
        pytest

  lint:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: checkout-repo
      uses: actions/checkout@v4

    - name: install-python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: make venv - get dependencies - run pylint
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        cd api
        pip install -r requirements.txt
        pylint --fail-under=8 --ignore-patterns=test_\.\* ./*.py
        cd ..
        cd pipeline
        pip install -r requirements.txt
        pylint --fail-under=8 --ignore-patterns=test_\.\* ./*.py
        cd ..
        cd database
        pip install -r requirements.txt
        pylint --fail-under=8 --ignore-patterns=test_\.\* ./*.py



  