name: Continuous Integration Workflow

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: checkout-repo
      uses: actions/checkout@v4

    - name: install-python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: make venv - get dependencies - run pytest
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        cd pipeline
        pip install -r requirements.txt
        pytest

  lint:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: checkout-repo
      uses: actions/checkout@v4

    - name: install-python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: make venv - get dependencies - run pylint
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        cd pipeline
        pip install -r requirements.txt
        pylint --fail-under=8 --ignore-patterns=test_\.\* ./*.py

  